# +------------------------------------------------------+ #
# |                 Jackpot (Configuration)              | #
# +------------------------------------------------------+ #
# If you have problems, join the Jackpot help support channel:
# https://discord.gg/gFwVVTE
# -----------------------------------------------------------
# Use these placeholders to display information:
# -
# {amount} ---> Amount of tickets purchased.
# {price} ---> Price for tickets purchased.
# -
# {timer} ---> Total time remaining till jackpot draw.
# {total-value} ---> Total value of current jackpot.
# {tax} ---> Jackpot tax percentage.
# {total-tickets} ---> Total amount of jackpot tickets.
# {player-tickets} ---> Number of jackpot tickets purchased by the player.
# {player-percent} ---> The percentage change the player will win the draw.
# -
# {winner} ---> The player name of the current jackpot draw winner.
# {prize} ---> The current jackpot draw prize.
# -----------------------------------------------------------
# IMPORTANT NOTES:
#    > Wrap your text in '' (quotes) if using color codes.
#    > All time values are in seconds.
#    > A tax-percent value of 0.10 is a 10% tax.
# -----------------------------------------------------------
jackpot:
  ticket-price: 1000
  draw-time: 3600
  tax-percent: 0.1
  warnings:
    - 1800
    - 600
    - 60
  confirm-gui: true
messages:
  buy-ticket: §aYou successfully purchased {amount} tickets for ${price}!
  cannot-afford: §cYou cannot afford the total price of ${price} for {amount} tickets!
  jackpot-info:
    - ''
    - '&e&lSERVER LOTTERY'
    - ''
    - '&fJackpot Value: &a${total-value} &7[-{tax}% Tax]'
    - '&fTickets Sold: &e{total-tickets}'
    - '&fYour Tickets: &c{player-tickets} &7[{player-percent}%]'
    - ''
    - '&fNext Winner in &e&n{timer}&f!'
    - ''
  jackpot-results:
    - ''
    - '&c&lLOTTERY RESULTS'
    - ''
    - '&fCongratulations to &e{winner} &ffor winning the lottery!'
    - '&fA prize of &a${prize} &fhas been added to their balance.'
    - ''
  jackpot-warning:
    - ''
    - '&e&lSERVER LOTTERY WARNING'
    - ''
    - '&fA lottery valued at &a${total-value} &fis drawing in &e{timer}&f!'
    - '&7To enter, use &f/lottery buy &7to purchase a ticket!'
    - ''
confirm-gui:
  title: Confirm | {amount} Tickets
  confirm-button:
    material: LIME_STAINED_GLASS_PANE
    name: '&a&lCONFIRM PURCHASE'
    lore:
      - '&8Description'
      - ''
      - '&fClick to &cconfirm &fpurchase of'
      - '&e{amount} &fticket(s) for &a${price}&f!'
  cancel-button:
    material: RED_STAINED_GLASS_PANE
    name: '&c&lCANCEL PURCHASE'
    lore:
      - '&8Description'
      - ''
      - '&fClick to &ccancel &fpurchase of'
      - '&e{amount} &fticket(s) for &a${price}&f!'
  center-button:
    material: BOOK
    name: '&e&lCONFIRMING YOUR PURCHASE'
    lore:
      - '&8Description'
      - ''
      - '&fSelect whether you would like to'
      - '&aconfirm &for &ccancel &fyour ticket purchase.'
  cancel-message: '&cYou have canceled your ticket purchase!'
